[install]
is_configured = 0

[ui]
is_visible = 1
label = Cisco Webex App for Splunk

[launcher]
author = FDSE
description = The Cisco Webex App for Splunk provides the interface for searches, reports, and dashboards for your Cisco Webex environment. It works in concert with Cisco Webex Add-on for Splunk, which connects to your Cisco Webex data, to enable you to monitor, manage, and troubleshoot your Webex service from a single application.
version = 2.0.0

[package]
id = cisco_webex_meetings_app_for_splunk
check_for_updates = 1

[id]
version = 2.0.0
name = cisco_webex_meetings_app_for_splunk