[webex_meeting]
definition = index=wx
iseval = 0

[webex_calling]
definition = index=wxc
iseval = 0

[webex_contact_center]
definition = index=wxcc
iseval = 0

[webex_indexes]
definition = `webex_meeting` OR `webex_calling` OR `webex_contact_center`
iseval = 0
